data:
  images: "../data/images/mscoco/train2014/"
  val_images: "../data/images/mscoco/val2014/"
  texts: "../data/text/"
  masks: "../data/instances/"

train_steps: 200000
model_save_path: "./grid_policy.pt"
